# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.22"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.22"
  i386: "ghcr.io/home-assistant/i386-base-python:3.13-alpine3.22"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: bundle2mqtt add-on"
  org.opencontainers.image.description: "bundle2mqtt"
  org.opencontainers.image.source: "https://github.com/stokworks/bundle-luxor-2-mqtt"
  org.opencontainers.image.licenses: "ISC"
args:
  TEMPIO_VERSION: "2024.11.2"